name: Java CI with Maven

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test with Maven
      run: mvn -B clean package --file pom.xml

    - name: Upload Compiled JAR
      uses: actions/upload-artifact@v4
      with:
        name: java-app-executable
        path: target/java-app-1.0-SNAPSHOT.jar
